[project]
name = "efficient-direct"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cvxpy>=1.7.4",
    "matplotlib>=3.10.7",
    "networkx>=3.6",
    "numpy>=2.3.5",
]
